name: Central schema change reporting

on:
  workflow_dispatch:

jobs:
  resolve-tags:
    name: Resolve inventory tags
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.pick.outputs.latest }}
      previous: ${{ steps.pick.outputs.previous }}
    steps:
      - name: Resolve latest & previous tags from mod-inventory-storage
        id: pick
        shell: bash
        run: |
          set -euo pipefail
          git ls-remote --tags https://github.com/folio-org/mod-inventory-storage.git \
            | awk '{print $2}' \
            | sed -n 's#refs/tags/##p' \
            | sed 's/\^{}$//' \
            | sort -V -r > /tmp/tags.txt

          LATEST=$(sed -n '1p' /tmp/tags.txt || true)
          PREV=$(sed -n '2p' /tmp/tags.txt || true)

          if [[ -z "$LATEST" ]]; then
            echo "No tags found in mod-inventory-storage" >&2
            exit 1
          fi

          echo "latest=$LATEST" >> "$GITHUB_OUTPUT"
          echo "previous=$PREV" >> "$GITHUB_OUTPUT"

          echo "Resolved latest tag: $LATEST"
          echo "Resolved previous tag: ${PREV:-<none>}"

  call-inventory:
    name: Call mod-inventory-storage reporting
    needs: resolve-tags
    uses: folio-org/mod-inventory-storage/.github/workflows/schema-changes-reporting.yml@main
    with:
      ref: refs/tags/${{ needs.resolve-tags.outputs.latest }}
      ref_name: ${{ needs.resolve-tags.outputs.latest }}
      previous_tag: ${{ needs.resolve-tags.outputs.previous }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}